name: Update Telegram Photos

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

jobs:
  update-photos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Test Telegram API connection
      run: |
        curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getMe" | jq .
        
    - name: Fetch photos from Telegram
      run: |
        node .github/scripts/telegram-fetch.js
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      
    - name: Verify photos file
      run: |
        if [ -f "data/photos.json" ]; then
          echo "Photos file exists"
          echo "File size: $(wc -c < data/photos.json) bytes"
          echo "Photo count: $(jq length data/photos.json || echo 0)"
        else
          echo "Photos file not found"
          exit 1
        fi
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/photos.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update photos from Telegram ($(date))"
          git push
        fi
