name: Update Telegram Photos

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours

jobs:
  update-photos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install node-fetch@2.6.7
      
    - name: Debug environment
      run: |
        echo "Bot token starts with: ${TELEGRAM_BOT_TOKEN:0:10}..."
        echo "Channel ID: $TELEGRAM_CHANNEL_ID"
        
    - name: Fetch photos from Telegram
      run: node .github/scripts/fetch-photos.js
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      
    - name: Check if photos were found
      run: |
        if [ -f "data/photos.json" ]; then
          echo "Photos file exists"
          echo "File size: $(wc -c < data/photos.json) bytes"
          echo "Photo count: $(jq length data/photos.json)"
        else
          echo "Photos file not found"
          exit 1
        fi
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/photos.json
        git diff --staged --quiet || git commit -m "Update photos from Telegram"
        git push
